### ISSUE TITLE
Updating Tests - Types not recognized

### ISSUE THREAD

**Issue by enmiller94** [gitslaton/HARIS#34]
@skiadas
We were updating our test file and got this error:
File "tests.ml", line 1: Error: Reference to undefined global `Types'         

We know we have to update the outputs to include the types and the values so we updated the first test (line 4) and received this error.

**Comment by skiadas** [comment]
Hm I did not have any problems, with the two lines:

```
#load "types.cmo";;
#use "tests.ml";;
```

Do those not work? Or are you trying to run your tests in some other way?

**Comment by gitslaton** [comment]
Not sure what was happening before, but it works fine now.
